CREATE TABLE ACCOUNT (
    ACCOUNT_NUMBER VARCHAR(255) PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    BALANCE DOUBLE PRECISION DEFAULT 0
);

INSERT INTO ACCOUNT (
    ACCOUNT_NUMBER,
    NAME,
    BALANCE
) VALUES (
    '123456',
    'Alice',
    1000
);

INSERT INTO ACCOUNT (
    ACCOUNT_NUMBER,
    NAME,
    BALANCE
) VALUES (
    '654321',
    'Bob',
    2000
);

INSERT INTO ACCOUNT (
    ACCOUNT_NUMBER,
    NAME,
    BALANCE
) VALUES (
    '789012',
    'Charlie',
    1500
);